require 'pry'
require 'nokogiri'
require 'open-uri'
require 'colorize'
require 'artii'
require 'console_table'
require 'text'

require_relative '../lib/travel_guide/scraper'
require_relative '../lib/travel_guide/place'
require_relative '../lib/travel_guide/cli'
require_relative '../lib/travel_guide/version'
